# data id: test-server.yaml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.68.100:8848
    sentinel:
      transport:
        dashboard: 192.168.68.100:8080
hello:
  name: 张三
settings:
  name1: 李四
  name2: 王五
  name3: 赵六
