# data id: test-server.yaml
spring:
  jpa:
    show-sql: true
  zipkin:
    base-url: http://192.168.61.100:9411
    discoveryClientEnabled: false
  sleuth:
    sampler:
      probability: 1.0 # 采样率，模式0.1，也就是10%，为了便于观察效果，改为1.0，也就是100%。生产环境建议保持默认。
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.61.100:8848
    sentinel:
      transport:
        dashboard: 192.168.61.100:9001
hello:
  name: 张三
settings:
  name1: 李四
  name2: 王五
  name3: 赵六